//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeattleCityVehicles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeattleCityVehiclesEntities : DbContext
    {
        public SeattleCityVehiclesEntities()
            : base("name=SeattleCityVehiclesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Active_PHEVs> Active_PHEVs { get; set; }
        public virtual DbSet<DepartmentName> DepartmentNames { get; set; }
        public virtual DbSet<FuelType> FuelTypes { get; set; }
        public virtual DbSet<Sold_Fleet_Equipment> Sold_Fleet_Equipment { get; set; }
        public virtual DbSet<VehicleMake> VehicleMakes { get; set; }
    }
}
