//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeattleCityVehicles
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleMake()
        {
            this.Active_PHEVs = new HashSet<Active_PHEVs>();
            this.Sold_Fleet_Equipment = new HashSet<Sold_Fleet_Equipment>();
        }
    
        public int VehicleMakeKey { get; set; }
        public string VehicleMake1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active_PHEVs> Active_PHEVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sold_Fleet_Equipment> Sold_Fleet_Equipment { get; set; }
    }
}
