USE [master]
GO

 

/****** Object:  Database [SeattleCityVehicles]    Script Date: 5/23/2021 2:02:38 PM ******/
CREATE DATABASE [SeattleCityVehicles]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SeattleCityVehicles', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SeattleCityVehicles.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SeattleCityVehicles_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SeattleCityVehicles_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

 

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SeattleCityVehicles].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

 

ALTER DATABASE [SeattleCityVehicles] SET ANSI_NULL_DEFAULT OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET ANSI_NULLS OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET ANSI_PADDING OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET ANSI_WARNINGS OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET ARITHABORT OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET AUTO_CLOSE OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET AUTO_SHRINK OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET AUTO_UPDATE_STATISTICS ON 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET CURSOR_DEFAULT  GLOBAL 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET NUMERIC_ROUNDABORT OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET QUOTED_IDENTIFIER OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET RECURSIVE_TRIGGERS OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET  DISABLE_BROKER 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET TRUSTWORTHY OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET PARAMETERIZATION SIMPLE 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET READ_COMMITTED_SNAPSHOT OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET HONOR_BROKER_PRIORITY OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET RECOVERY FULL 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET  MULTI_USER 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET PAGE_VERIFY CHECKSUM  
GO

 

ALTER DATABASE [SeattleCityVehicles] SET DB_CHAINING OFF 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET DELAYED_DURABILITY = DISABLED 
GO

 

ALTER DATABASE [SeattleCityVehicles] SET  READ_WRITE 
GO
